from pydantic import BaseModel
from uuid import UUID
from datetime import datetime
from typing import Optional
from app.db.models import Mode   # enum containing GENERAL, PROFESSOR, COLLEGE_BUDDY, ROASTER


class ChatCreate(BaseModel):
    name: Optional[str] = "New Chat"
    # chat title, default is "New Chat" if user doesn't provide one

    mode: Mode = Mode.GENERAL
    # assistant mode for this chat
    # user can choose only from the enum values


class ChatResponse(BaseModel):
    id: UUID                # unique chat id generated by database
    name: str               # chat name
    mode: Mode              # which AI personality this chat uses
    created_at: datetime    # timestamp when chat was created
    user_id: UUID           # owner of the chat

    class Config:
        from_attributes = True
        # converts SQLAlchemy Chat object → ChatResponse automatically


class ChatUpdate(BaseModel):
    name: Optional[str] = None
    # used when user renames chat

    mode: Optional[Mode] = None
    # optional change of chat mode