import requests
from typing import Dict, Deque
from dotenv import load_dotenv
import os

load_dotenv()

def generate_response(request : Deque[Dict], sys_prompt : Dict) -> str:
    # request.appendleft(sys_prompt) instead make a separate list
    payload_messages = [sys_prompt] + list(request)
    response = requests.post(
        url = os.getenv("LLM_URL"),
        json = {
            "model" : os.getenv("LLM_MODEL"),
            "stream" : False,
            # "messages" : request # depending upon implicit conversion (not fine). Dq is not json serializable
            "messages" : payload_messages
        }
    )
 
    output = response.json()
    request.append(output['message'])
    # request.popleft() No need if we handle a separate list "payload_messages"

    return output['message']['content'] # initially attempted code

# if we send requests like these (below code), llm would be able to understand the past context of the chat, note that there are three types of roles.
# 1. user --> Maps to the text we would fetch from the frontend
# 2. assistant --> Maps to the text generated by the LLM corresponding to a request.
# 3. system --> Maps to the prompts given by system to the LLM

# Also there should be a maintained "messages" deque of fixed size.
# The size would determine the context upto which the LLM can remember things (general comprehension) or it is the context that we would pass with the latest request (true reason of why LLMs behave as if they know).
# Also we do not have to push system prompts in the messages deque as they must be applied to a chat no matter how many messages are there in the chat.
# request = [
#     {"role" : "user", "content" : "Explain binary search"},
#     {
#         "role" : "assistant",
#         "content" : """
#             Binary Search is a divide-and-conquer algorithm used for finding an element in a sorted array by repeatedly dividing the portion of the array being searched in half. Here's how it works:

#             1. Compare the target value to the middle element of the sorted array.
#             2. If they are not equal, check whether the target is less than or greater than the mid-element.
#             3. Based on this comparison, discard either the left half or right half of the array (not including the midpoint). The remaining part will be a smaller subset that also needs to find our element; hence we recursively apply steps 1 and 2 in it until we are done with recursion calls or narrowed down to one possible point where an equal value may exist.
#             4. If you reached this state because there's no more space left (i.e., the array length is reduced to just one element), check whether that remaining single-element matches our target - if yes, we found it! Otherwise, continue with another recursive search on other halves of subarray(if any).
#             5. Repeat these steps until either you find your desired value or have searched all possible locations in the array and determine that the element is not present within this particular sorted list itself (though there could still exist outside elsewhere untouched) without needing further exploration/expansion beyond what has been done here already during execution course of time spent traversing elements inside while searching.

#             Binary search runs with a logarithmic runtime, specifically O(log n), where 'n' represents the size of your input list or array being searched upon (in terms). This efficiency results from continually narrowed-down sections in our recursive procedure due to dividing work into half each time until either finding desired element at hand/ending up without it after exhaustively checked all possibilities.
#         """
#     },
#     {"role" : "user", "content" : "Okay, now calculate the time complexity."}
# ]

# print(generate_response(request))

# LLMs do not have any memory to save previous context. That is they are stateless.